name: Test if statement
on:
  push:
    branches:
      - development
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
jobs:
  docker:
    name: Testing labels
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build_containers')
    steps:
      - name: Checkout
        uses: actions/checkout@v4